# Generated by Django 5.1.4 on 2026-06-21 22:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('join_code', models.CharField(editable=False, max_length=8, unique=True)),
                ('mode', models.CharField(choices=[('solo', 'Yakka'), ('class', 'Sinf'), ('pair', 'Juft'), ('team', 'Jamoa')], default='solo', max_length=8)),
                ('status', models.CharField(choices=[('waiting', 'Kutilmoqda'), ('active', 'Faol'), ('ended', 'Tugagan')], default='waiting', max_length=8)),
                ('max_players', models.IntegerField(default=30)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='content.contentitem')),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sessions_gamesession',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=64)),
                ('team_number', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('answers', models.JSONField(blank=True, default=list)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='game_sessions.gamesession')),
            ],
            options={
                'db_table': 'sessions_gameparticipant',
                'ordering': ['-score', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('duration_sec', models.IntegerField(default=0)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_games', to='content.contentitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sessions_usergame',
                'ordering': ['-played_at'],
            },
        ),
    ]
