# Generated by Django 5.1.4 on 2026-06-21 21:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('staff', 'Staff'), ('teacher', "O'qituvchi")], default='staff', max_length=8)),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('pending', "Ko'rib chiqilmoqda"), ('published', 'Chop etilgan'), ('rejected', 'Rad etilgan')], default='draft', max_length=10)),
                ('play_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'content_contentitem',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameEngine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('default_config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'content_gameengine',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('label', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'content_grade',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'content_subject',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=128)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'content_topic',
                'ordering': ['grade_id', 'order'],
            },
        ),
    ]
