# Generated by Django 5.1.4 on 2026-06-21 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='content.gameengine'),
        ),
        migrations.AddField(
            model_name='topic',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.grade'),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.subject'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.topic'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('subject', 'grade', 'slug')},
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['topic', 'engine'], name='content_con_topic_i_6b0fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['status'], name='content_con_status_c88a23_idx'),
        ),
    ]
