# Generated by Django 5.1.4 on 2026-06-29 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_phone_alter_user_telegram_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click')], max_length=8)),
                ('plan', models.CharField(max_length=8)),
                ('amount', models.BigIntegerField()),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('order_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('cancelled', 'Bekor qilingan')], default='pending', max_length=10)),
                ('provider_txn_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('provider_time', models.BigIntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('perform_time', models.DateTimeField(blank=True, null=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.IntegerField(blank=True, null=True)),
                ('raw_request', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'state'], name='payments_tr_provide_4ad8c0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_txn_id__isnull', False)), fields=('provider', 'provider_txn_id'), name='uq_provider_txn')],
            },
        ),
    ]
